import Link from "next/link";
import ThemeToggle from "@/app/components/ThemeToggle";
import styles from "../page.module.css";

export default function TermsOfService() {
  return (
    <div className={styles.void}>
      <div className={styles.shell}>
        {/* Navigation */}
        <div className={styles.navRow}>
          <div className={styles.navPill}>
            <Link href="/" className={styles.brand}>
              <span className={styles.brandMark} />
              <span className={styles.brandName}>API Sentinel</span>
            </Link>
            <div className={styles.navSpacer} />
            <div className={styles.navActions}>
              <ThemeToggle />
              <Link href="/" className={styles.btnGhost} style={{ padding: "8px 16px", textDecoration: "none", fontSize: "14px" }}>
                Home
              </Link>
            </div>
          </div>
        </div>

        {/* Content Container */}
        <div className={styles.prose}>
          <h1>Terms of Service</h1>
          <p className={styles.proseMeta}>Last updated: August 5, 2026</p>

          <section>
            <h2>1. Beta Software</h2>
            <p>
              API Sentinel is currently offered as beta software. The service is provided on an "as-is" and "as-available" basis, without warranty of any kind, express or implied.
            </p>
          </section>

          <section>
            <h2>2. AI-Generated Patches and Pull Requests</h2>
            <p>
              Compatibility patches generated by API Sentinel are opened as draft pull requests (DRAFT PRs) in your repositories. These patches require manual human review and approval before they can be merged.
            </p>
          </section>

          <section>
            <h2>3. User Responsibility</h2>
            <p>
              You are solely responsible for reviewing, testing, and merging any code patches provided by API Sentinel. We assume no liability for compatibility issues, bugs, or build failures in code merged into your repository.
            </p>
          </section>

          <section>
            <h2>4. Relationship with Stripe</h2>
            <p>
              API Sentinel is an independent tool developed for Stripe integrations. We are not affiliated with, authorized, maintained, sponsored, or endorsed by Stripe.
            </p>
          </section>

          <section>
            <h2>5. Pricing and Service Availability</h2>
            <p>
              The service is free to use during the beta period. We reserve the right to modify, suspend, or discontinue any aspect of the service at any time without notice.
            </p>
          </section>
        </div>

        {/* Footer */}
        <footer className={styles.footer}>
          <div className={styles.footerInner}>
            <div className={styles.footerBrand}>
              <span className={styles.brandMark} />
              API Sentinel
            </div>
            <p className={styles.disclaimer}>
              api-sentinel is an independent tool for Stripe developers. Not affiliated with or endorsed by Stripe.
            </p>
            <span className={styles.footerCopy}>&copy; {new Date().getFullYear()}</span>
          </div>
        </footer>
      </div>
    </div>
  );
}
